### ISSUE TITLE
Chat-bot sends back the same message you sent at the end of the reply

### ISSUE THREAD

**Issue by Alex61NN5** [yuriburger/ng-chatbot-demo#1]
Hey There,

Basically all I have done is downloaded the sample project and have entered my own API Key.

Now what happens is I send a message 'Hi Chatbot' for example and then I get my chatbots expected response but then I get another message of 'Hi Chatbot' again but from the chat bot

so my chat looks like this

```
     'Hi Chatbot' - User

'Hey User' - Chatbot

'Hi Chatbot' - Chatbot
```

It looks the chatbot is just returning your original sent message...

Do you know how I could solve this issue?

**Comment by Alex61NN5** [comment]
Would like an update on this please

**Comment by yuriburger** [comment]
Hi, 
Could it be, that you are not filtering the messages for your specific bot name? Please check setup.ts and see if you have a filter on the incoming messages.

Hope this helps,

/Y.
